# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "build"

[context.branch-deploy]
  command = "cp static/_branchdeploy_headers public/_headers && yarn build"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

  [plugins.inputs]

	  # The base url of your site (optional, default = main URL set in Netlify)
	  baseUrl = "https://galleon.community"

	  # Path to the sitemap URL (optional, default = /sitemap.xml)
	  sitemapPath = "/sitemap.xml"

	  # Enabled providers to submit sitemap to (optional, default = 'google', 'bing', 'yandex'). Possible providers are currently only 'google', 'bing', 'yandex'.
	  providers = [
		  "google",
		  "bing",
		  "yandex"
	  ]

[[plugins]]
  package = "netlify-plugin-image-optim"

[[plugins]]
package = "@commandbar/netlify-plugin-commandbar"